DROP TABLE USER;
CREATE TABLE USER(
    USER_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    USER_NAME VARCHAR(36)    COMMENT '登录账户' ,
    USER_PWD VARCHAR(36)    COMMENT '登录密码' ,
    USER_NICKNAME VARCHAR(36)    COMMENT '用户昵称' ,
    USER_OPEN_ID VARCHAR(36)    COMMENT '微信openId' ,
    USER_GENDER INT    COMMENT '用户性别' ,
    USER_AGE INT    COMMENT '用户年龄' ,
    USER_CAREER VARCHAR(36)    COMMENT '用户职业' ,
    USER_TEL VARCHAR(36)    COMMENT '用户手机号码' ,
    USER_ADDR VARCHAR(128)    COMMENT '用户地址' ,
    USER_AVATAR_URL VARCHAR(255)    COMMENT '微信头像' ,
    USER_IF_BANNED VARCHAR(1)    COMMENT '是否被禁用' ,
    USER_IF_ORGAN VARCHAR(1)    COMMENT '招募资质' ,
    USER_IF_SUPER VARCHAR(1)    COMMENT '运维身份' ,
    USER_REG_TIME VARCHAR(36)    COMMENT '注册时间' ,
    USER_LONGITUDE DECIMAL(32,10)    COMMENT '登陆经度' ,
    USER_LATITUDE DECIMAL(32,10)    COMMENT '登陆纬度' ,
    SESSION_KEY VARCHAR(36)    COMMENT '登录状态码' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '用户表 ';

ALTER TABLE USER COMMENT '用户表';
DROP TABLE ORGANIZATION;
CREATE TABLE ORGANIZATION(
    ORGAN_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    USER_ID VARCHAR(36)    COMMENT '所属用户ID' ,
    ORGAN_NAME VARCHAR(36)    COMMENT '组织名称' ,
    ORGAN_ADDR VARCHAR(36)    COMMENT '组织地址' ,
    ORGAN_TEL VARCHAR(36)    COMMENT '组织电话' ,
    ORGAN_INTRO VARCHAR(36)    COMMENT '组织简介' ,
    ORGAN_STATUS VARCHAR(36)    COMMENT '组织申请状态 0：提交申请待审核；1：通过；2：失败' ,
    PRIMARY KEY (ORGAN_ID)
) COMMENT = '组织机构表 ';

ALTER TABLE ORGANIZATION COMMENT '组织机构表';
DROP TABLE ACTIVITY;
CREATE TABLE ACTIVITY(
    ACT_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    USER_ID VARCHAR(36)    COMMENT '发起者ID' ,
    ACT_NAME VARCHAR(36)    COMMENT '活动名称' ,
    ACT_ADDR VARCHAR(36)    COMMENT '活动地址' ,
    ACT_REC_BEGIN VARCHAR(36)    COMMENT '申请开始时间' ,
    ACT_REC_END VARCHAR(36)    COMMENT '申请截止时间' ,
    ACT_TIME_BEGIN VARCHAR(36)    COMMENT '活动开始时间' ,
    ACT_TIME_END VARCHAR(36)    COMMENT '活动截止时间' ,
    ACT_USER_NUM VARCHAR(36)    COMMENT '需求人数' ,
    ACT_DEMANDS VARCHAR(1024)    COMMENT '活动内容与要求' ,
    ACT_STATUS VARCHAR(36)    COMMENT '活动状态 0：已提交；1：招募中；2：招募成功待开始；3：招募失败待处理；4：已取消；5：进行中；6：已结束' ,
    CHECK_LONGITUDE DECIMAL(32,10)    COMMENT '签到经度' ,
    CHECK_LATITUDE DECIMAL(32,10)    COMMENT '签到纬度' ,
    PRIMARY KEY (ACT_ID)
) COMMENT = '志愿活动表 ';

ALTER TABLE ACTIVITY COMMENT '志愿活动表';
DROP TABLE USER_ACT;
CREATE TABLE USER_ACT(
    USER_ACT_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    USER_ID VARCHAR(36)    COMMENT '用户ID' ,
    ACT_ID VARCHAR(36)    COMMENT '活动ID' ,
    APPLY_TIME VARCHAR(36)    COMMENT '申请时间' ,
    APPLY_STATUS VARCHAR(36)    COMMENT '申请状态 0：已提交申请；1：活动已取消；2：活动待开始；3：待签到；4：进行中；5：已完成' ,
    CHECK_TIME VARCHAR(36)    COMMENT '签到时间' ,
    CHECK_LONGITUDE DECIMAL(32,10)    COMMENT '签到经度' ,
    CHECK_LATITUDE DECIMAL(32,10)    COMMENT '签到纬度' ,
    REVIEW_CONTENT VARCHAR(1024)    COMMENT '评价内容' ,
    REVIEW_TIME VARCHAR(36)    COMMENT '评价时间' ,
    PRIMARY KEY (USER_ACT_ID)
) COMMENT = '用户志愿活动表 ';

ALTER TABLE USER_ACT COMMENT '用户志愿活动表';
DROP TABLE REPORT;
CREATE TABLE REPORT(
    REPORT_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    USER_ID VARCHAR(36)    COMMENT '用户ID' ,
    REPORTED_ID VARCHAR(36)    COMMENT '被投诉的ID' ,
    REPORT_TYPE VARCHAR(1)    COMMENT '被投诉者类型 0用户；1活动' ,
    REPORT_REASON VARCHAR(1024)    COMMENT '投诉文本内容' ,
    REPORT_TIME VARCHAR(36)    COMMENT '投诉时间' ,
    REPORT_STATUS VARCHAR(1)    COMMENT '投诉处理状态 0待处理；1投诉成功；2投诉失败' ,
    REPORT_HANDLER VARCHAR(36)    COMMENT '投诉处理人' ,
    PRIMARY KEY (REPORT_ID)
) COMMENT = '投诉表 ';

ALTER TABLE REPORT COMMENT '投诉表';
DROP TABLE FILE;
CREATE TABLE FILE(
    FILE_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    LINK_ID VARCHAR(255)    COMMENT '关联ID' ,
    LINK_TYPE VARCHAR(36)    COMMENT '关联类型' ,
    FILE_ADDR VARCHAR(36)    COMMENT '文件路径' ,
    FILE_TIME VARCHAR(36)    COMMENT '上传时间' ,
    PRIMARY KEY (FILE_ID)
) COMMENT = '媒体文件表 ';

ALTER TABLE FILE COMMENT '媒体文件表';
DROP TABLE Parameter;
CREATE TABLE Parameter(
    PARAM_ID VARCHAR(36) NOT NULL   COMMENT '主键ID 本表主键ID' ,
    PARAM_KEY VARCHAR(36)    COMMENT '参数名' ,
    PARAM_VALUE VARCHAR(128)    COMMENT '参数值' ,
    PRIMARY KEY (PARAM_ID)
) COMMENT = '参数表 ';

ALTER TABLE Parameter COMMENT '参数表';
